export enum ProposalStatus {
  CONFIRMED = 'CONFIRMED',
  CANCELED = 'CANCELED',
  PENDING = 'PENDING',
  OPTION = 'OPTION',
}

export enum CaptureStatus {
  NOT_DISPATCHED = 'NOT_DISPATCHED',
  AWAITING_FILL = 'AWAITING_FILL',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}

export enum PassengerSlotStatus {
  PENDING = 'PENDING',
  FILLED = 'FILLED',
}

export enum SyncStatus {
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}

export enum DispatchMode {
  EMAIL = 'EMAIL',
  MANUAL_LINK = 'MANUAL_LINK',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_DELETED = 'USER_DELETED',
  SYNC_STARTED = 'SYNC_STARTED',
  SYNC_COMPLETED = 'SYNC_COMPLETED',
  SYNC_FAILED = 'SYNC_FAILED',
  CAPTURE_DISPATCHED = 'CAPTURE_DISPATCHED',
  CAPTURE_LINK_GENERATED = 'CAPTURE_LINK_GENERATED',
  EMAIL_SENT = 'EMAIL_SENT',
  EMAIL_FAILED = 'EMAIL_FAILED',
  CLIENT_ACCESSED = 'CLIENT_ACCESSED',
  FORM_SAVED = 'FORM_SAVED',
  FORM_COMPLETED = 'FORM_COMPLETED',
  ADMIN_EDITED = 'ADMIN_EDITED',
  EXPORT_GENERATED = 'EXPORT_GENERATED',
  PHOTO_UPLOADED = 'PHOTO_UPLOADED',
}
